### ISSUE TITLE
click-odoo-initdb trying to apply module migrations

### ISSUE THREAD

**Issue by joao-p-marques** [acsone/click-odoo-contrib#91] opened 2021-03-26 09:19 UTC
I am getting an error when running `click-odoo-initdb` and passing a module to install.
The error occurs because it tries  to run migrations even though the tables didn't exist in the DB.

### Steps to reproduce:
1. Drop any existing DB: `click-odoo-dropdb devel`
2. Init the new DB with the `queue_job` module: `click-odoo-initdb -n devel -m queue_job`

Error:
```
2021-03-26 08:10:04,225 1 WARNING ? odoo.modules.registry: The option --unaccent was given but no unaccent() function was found in database. 
2021-03-26 08:10:21,704 1 ERROR devel odoo.sql_db: bad query: 
            ALTER TABLE queue_job
            ADD COLUMN records text;
        
ERROR: relation "queue_job" does not exist
 
2021-03-26 08:10:21,705 1 ERROR devel odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 488, in load_modules
    loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 190, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/custom/src/odoo/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/opt/odoo/auto/addons/queue_job/migrations/13.0.3.2.0/pre-migration.py", line 16, in migrate
    """
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "queue_job" does not exist

2021-03-26 08:10:21,705 1 ERROR devel click_odoo.env_options: exception 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/click_odoo/env_options.py", line 218, in _invoke
    return self.org_invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click_odoo_contrib/initdb.py", line 432, in main
    odoo_createdb(new_database, demo, module_names, True)
  File "/usr/local/lib/python3.6/site-packages/click_odoo_contrib/initdb.py", line 77, in odoo_createdb
    Registry.new(dbname, force_demo=demo, update_module=True)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 488, in load_modules
    loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 190, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/custom/src/odoo/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/opt/odoo/auto/addons/queue_job/migrations/13.0.3.2.0/pre-migration.py", line 16, in migrate
    """
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "queue_job" does not exist

Error: relation "queue_job" does not exist

ERROR: 1
```

If I do, OTOH:
1. Drop any existing DB: `click-odoo-dropdb devel`
2. Init the new DB without modules: `click-odoo-initdb -n devel -m base`
3. Install `queue_job`

Everything works

### Info

Odoo version: 13.0

cc @Yajo

**Comment by sbidoul** [comment] 2021-04-13 20:46
I can't reproduce this. Can you provide more details ?

**Comment by joao-p-marques** [comment] 2021-04-15 08:11
@sbidoul I just found the reason: I was using the https://github.com/OCA/OpenUpgrade remote as the Odoo version, so the migrations were always triggered, although I don't know if this is an expected behavior or not.
Thanks for the response!

**Comment by sbidoul** [comment] 2021-04-15 10:16
Ok thanks for the feedback. I don't think this in scope for this project to work with OpenUpgrade, so closing.

**Closed by sbidoul** 2021-04-15 10:16 UTC
Labels: question
